# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test readme files

on:
  push:
    paths:
      - 'cypress/**'
    branches:
      - main
  pull_request:
    paths:
      - 'cypress/**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Cypress example
        uses: docker/build-push-action@v5
        with:
          context: ./cypress
          file: ./cypress/Dockerfile
          push: false
          secrets: |
            "dotenv=${{ secrets.DOTENV }}"

  cypress-saucectl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Cypress example
        uses: docker/build-push-action@v5
        with:
          context: ./cypress
          file: ./cypress/Dockerfile.saucectl
          push: false
          secrets: |
            "dotenv=${{ secrets.DOTENV }}"
