# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test readme files

on:
  push:
    paths:
      - 'wd-java*/**'
    branches:
      - main
  pull_request:
    paths:
      - 'wd-java*/**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  wd-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build wd-java example
        uses: docker/build-push-action@v4
        with:
          context: ./wd-java
          file: ./wd-java/Dockerfile
          push: false
          secrets: |
            "dotenv=${{ secrets.DOTENV }}"

  wd-java-testng:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build wd-java-testng example
        uses: docker/build-push-action@v4
        with:
          context: ./wd-java-testng
          file: ./wd-java/Dockerfile
          push: false
          secrets: |
            "dotenv=${{ secrets.DOTENV }}"
