# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: StoryBook Tests

on:
  push:
    paths:
      - 'storybook*/**'
      - '.github/workflows/storybook.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'storybook*/**'
      - '.github/workflows/storybook.yml'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Storybook example
        uses: docker/build-push-action@v4
        with:
          context: ./storybook
          file: ./storybook/Dockerfile
          push: false
          secrets: |
            "dotenv=${{ secrets.DOTENV }}"
