# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: WDIO Android Tests

on:
  push:
    paths:
      - 'wdio-android-app/**'
      - '.github/workflows/wdio-android.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'wdio-android-app/**'
      - '.github/workflows/wdio-android.yml'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  wdio-native-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-type: [realdevice, emulator]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install saucectl
        uses: saucelabs/saucectl-run-action@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          skip-run: true

      - name: Pre-Upload App
        id: upload
        working-directory: ./wdio-android-app/
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: |
          APP_FILEID=$(saucectl storage upload ./app/SauceLabs-Demo-App.apk -o json | jq -r '.id')
          echo "APP_FILEID=${APP_FILEID}" >> $GITHUB_OUTPUT

      - name: Build wdio example
        uses: docker/build-push-action@v4
        with:
          context: ./wdio-android-app
          file: ./wdio-android-app/Dockerfile
          build-args:
            APP_FILEID=${{ steps.upload.outputs.APP_FILEID }}
            TYPE=${{ matrix.app-type }}
          push: false
          secrets: |
            "dotenv=${{ secrets.DOTENV }}"
